/*************************************************
 * Anthor  : LuoZhongYao@gmail.com
 * Modified: 2016 三月 24
 ************************************************/
#ifndef __UART_HANDLER_H__
#define __UART_HANDLER_H__

#include <avrcp.h>

typedef enum {
    CLI_RSP_INIT_OK,
    CLI_RSP_PHONEBOOK_START,
    CLI_RSP_PHONEBOOK_INFO,
    CLI_RSP_PHONEBOOK_END,

    /**************** Do not change the order ******************/
    CLI_RSP_CALLER_NUMBER,
    CLI_RSP_OUTGOING_NUMBER,
    CLI_RSP_INCOMMING_NUMBER,
    CLI_RSP_WAIT_NUMBER,

    CLI_RSP_DEVICE_NAME,
    CLI_RSP_DEVICE_PIN,
    CLI_RSP_HFP_CONNECTING,
    CLI_RSP_HFP_CONNECTED,
    CLI_RSP_HFP_OUTGOING,
    CLI_RSP_HFP_INCOMMING,
    CLI_RSP_HFP_ACTIVE,
    CLI_RSP_HFP_END,
    CLI_RSP_HFP_STATUS,
    CLI_RSP_HFP_DISCONNECTED,
    CLI_RSP_A2DP_DISCONNECTED,
    CLI_RSP_A2DP_STATUS,
    CLI_RSP_HFAV_STATUS,
    CLI_RSP_TRANSGER_STATUS,
    CLI_RSP_SCO_STATUS,
    CLI_RSP_MUTE,

    CLI_RSP_AVRCP_ATTRIBUTE_BASE,
    CLI_RSP_AVRCP_ATTRIBUTE_TITLE        = CLI_RSP_AVRCP_ATTRIBUTE_BASE + AVRCP_MEDIA_ATTRIBUTE_TITLE,
    CLI_RSP_AVRCP_ATTRIBUTE_ARTIST       = CLI_RSP_AVRCP_ATTRIBUTE_BASE + AVRCP_MEDIA_ATTRIBUTE_ARTIST,
    CLI_RSP_AVRCP_ATTRIBUTE_ALBUM        = CLI_RSP_AVRCP_ATTRIBUTE_BASE + AVRCP_MEDIA_ATTRIBUTE_ALBUM,
    CLI_RSP_AVRCP_ATTRIBUTE_NUMBER       = CLI_RSP_AVRCP_ATTRIBUTE_BASE + AVRCP_MEDIA_ATTRIBUTE_NUMBER,
    CLI_RSP_AVRCP_ATTRIBUTE_TOTAL_NUMBER = CLI_RSP_AVRCP_ATTRIBUTE_BASE + AVRCP_MEDIA_ATTRIBUTE_TOTAL_NUMBER,
    CLI_RSP_AVRCP_ATTRIBUTE_GENRE        = CLI_RSP_AVRCP_ATTRIBUTE_BASE + AVRCP_MEDIA_ATTRIBUTE_GENRE,
    CLI_RSP_AVRCP_ATTRIBUTE_PLAYING_TIME = CLI_RSP_AVRCP_ATTRIBUTE_BASE + AVRCP_MEDIA_ATTRIBUTE_PLAYING_TIME,
    CLI_RSP_AVRCP_PLAYBACK_POS,
    CLI_RSP_AVRCP_PLAY_STATUS,

    CLI_RSP_REMOTE_DEVICE_INFO,
    CLI_RSP_INQUIRY_DEVICE_INFO,
    CLI_RSP_INQUIRY_START,
    CLI_RSP_INQUIRY_END,
    CLI_RSP_PAIR_INFO,
    CLI_RSP_PAIR_EMPTY_INFO,
    CLI_RSP_PBAP_SUPPORT,

    CLI_RSP_BLE_NOTIFY,
    CLI_RSP_BLE_INFO,

    CLI_RSP_HID_STATUS,

    CLI_RSP_NOTHING,
}CLI_RSP_EVENT; 

extern void UartInit(void);

#endif

